### ISSUE TITLE
Requested template 'dev_console/index' not found!

### ISSUE THREAD

**Issue by dhruv-goel** [redvanworkshop/rvw_developers_core#35]
**Description**
In SFRA version I get the following:
            Wrapped com.demandware.beehive.core.internal.template.ServletAbortException: Requested template 'dev_console/index' not found! (rvw_dev_console/cartridge/controllers/Console.js#25)

In SiteGenesis version,
I get the following error:
An Error Occurred!
We're sorry that your order could not be placed. This probably happened due to a very high order volume or temporary connection errors. Please wait a few minutes and resubmit your order. We won't process your payment until your order is placed successfully. If you have further questions, please contact us via noreply@salesforce.com

**To Reproduce**
1. Follow the steps to add the cartridge to the sandbox
2. Upload the code
3. Hit the URL with Console-Show in the browser window

**Expected behavior**
Console Window Editor should open

**Comment by manifestinteractive** [comment]
@dhruv-goel Can you verify that you tried toggling your code version?  This looks like it is not finding the template, and if it is uploaded, then it is likely an issue with just needing to do that code version switch trick ( sometimes new cartridges don't 100% register unless you do this ).

This was covered in the README, but could have been missed:

**TROUBLESHOOTING**: Getting an error loading the console? You may need to temporarily switch Code Versions, then switch back to trigger the update in Business Manager.

**Comment by manifestinteractive** [comment]
Closing this out for now since the original poster did not respond, and we are unable to duplicate the issue.
